/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import clases.Asignatura;
import clases.ControladorAsignatura;
import clases.ControladorMetodologia;
import clases.ControladorSubUnidad;
import clases.ControladorUnidad;
import clases.ControladorUsuario;
import clases.ErrorPlanificacion;
import clases.Metodologia;
import clases.SubUnidad;
import clases.Unidad;
import clases.Usuario;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Enrique
 */
public class frmSubUnidadAgregar extends javax.swing.JFrame {
    
    String ruta_archivo="";
    DefaultComboBoxModel modeloSubUnidad=new DefaultComboBoxModel();
    /**
     * Creates new form frmAsignaturaAgregar
     */
    public frmSubUnidadAgregar() {
        initComponents();
        this.setLocationRelativeTo(null);
        rellenoCombo();
    }
    
    public void limpiar(){
        txtCodigo.setText("");
        txtNombre.setText("");
        txtPdf.setText("");
    }
    
    public void seleccionar_pdf() {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("pdf", "pdf");
        chooser.setFileFilter(filter);
        int se = chooser.showOpenDialog(this);
        if (se == 0) {
            this.txtPdf.setVisible(true);
            this.txtPdf.setText("" + chooser.getSelectedFile().getName());
            ruta_archivo = chooser.getSelectedFile().getAbsolutePath();

        } else {
        }
    }
    
    //---------------------creacion de combo--------------------------------
    public void rellenoCombo(){
         cmbSubUnidad.removeAll();
         modeloSubUnidad=new DefaultComboBoxModel();
        modeloSubUnidad.removeAllElements();
        Object[] opcion=new Object[6];
            ArrayList<Unidad> uni=new ArrayList<>();
        try {
            uni = ControladorUnidad.Buscar();
        } catch (ErrorPlanificacion ex) {
            Logger.getLogger(frmUnidadAgregar.class.getName()).log(Level.SEVERE, null, ex);
        }
            Iterator iterador=uni.iterator();
            
            while(iterador.hasNext()){
                
                opcion[0]=iterador.next();
                
                modeloSubUnidad.addElement(iterador.next());
                opcion[1]=iterador.next();
                opcion[2]=iterador.next();
                opcion[3]=iterador.next();
                opcion[4]=iterador.next();
                opcion[5]=iterador.next();
                
            }
            
            cmbSubUnidad.setModel(modeloSubUnidad);
        
     }  
    
    public void seleccionarPdf() {
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fi = new FileNameExtensionFilter("pdf", "pdf");
        j.setFileFilter(fi);
        int se = j.showOpenDialog(this);
        if (se == 0) {
//            this.btnPdf.setText("" + j.getSelectedFile().getName());
            ruta_archivo = j.getSelectedFile().getAbsolutePath();

        } else {
        }
    }
    
    public void guardar(){
        String codigo=txtCodigo.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lblAgregar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblCancelar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnPdf = new javax.swing.JButton();
        txtPdf = new javax.swing.JTextField();
        cmbSubUnidad = new javax.swing.JComboBox<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Unidad:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        lblAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        lblAgregar.setText("Agregar");
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarMouseClicked(evt);
            }
        });
        getContentPane().add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        jLabel7.setText("Agregar SubUnidad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 180, -1));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 180, -1));

        jTextField6.setText("jTextField1");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jLabel8.setText("Código:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        lblCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        lblCancelar.setText("Cancelar");
        lblCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarMouseClicked(evt);
            }
        });
        getContentPane().add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel10.setText("Archivo PDF:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        btnPdf.setText("Buscar Pdf");
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });
        getContentPane().add(btnPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 180, -1));

        txtPdf.setEditable(false);
        getContentPane().add(txtPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 260, -1));

        cmbSubUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbSubUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseClicked
        String id=txtCodigo.getText();
        String nombre=txtNombre.getText();
        String unidad=cmbSubUnidad.getSelectedItem().toString();
        String pdf=txtPdf.getText();
        
       
        
        
        
        if (id.isEmpty() && nombre.isEmpty() && pdf.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Rellene todos los campos por favor");
        }else{
            try{
                SubUnidad sub=new SubUnidad();
                sub.setIdSubUnidad(id);
                String idUnidad=ControladorSubUnidad.Obtener(unidad);
                sub.setNombre(nombre);
                sub.setNombrePdf(pdf);
                
                //Conviertiendo a bytes el pdf
                File ruta=new File(ruta_archivo);
                byte[] mipdf = new byte[(int) ruta.length()];
                InputStream input = new FileInputStream(ruta);
                input.read(mipdf);
                sub.setPdf(mipdf);
                
                sub.setIdUnidad(idUnidad);
                ControladorSubUnidad.Agregar(sub);
                JOptionPane.showMessageDialog(null,"Todo se ejecuto con exito");
                limpiar();
                } catch (ErrorPlanificacion ex) {
                    Logger.getLogger(frmSubUnidadAgregar.class.getName()).log(Level.SEVERE, null, ex);
                } catch (FileNotFoundException ex) {
                Logger.getLogger(frmSubUnidadAgregar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(frmSubUnidadAgregar.class.getName()).log(Level.SEVERE, null, ex);
            }
             
            }
    }//GEN-LAST:event_lblAgregarMouseClicked

    private void lblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseClicked
        frmSubUnidad meto=new frmSubUnidad();
        meto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblCancelarMouseClicked

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
        seleccionar_pdf();
    }//GEN-LAST:event_btnPdfActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
         int c=(int) evt.getKeyChar();
        char mayu=evt.getKeyChar();

        if ((c>=65 && c<=90) || (c>=97 && c<=122)  || (c==32) || (c==8) || (c >=48 && c<=57) || (c== (char)KeyEvent.VK_BACK_SPACE) || (c== (char)KeyEvent.VK_ENTER)) {
            if (Character.isLowerCase(mayu)) {
                String cadena=(""+mayu).toUpperCase();
                mayu=cadena.charAt(0);
                evt.setKeyChar(mayu);
            }
        }else{
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSubUnidadAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSubUnidadAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSubUnidadAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSubUnidadAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSubUnidadAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPdf;
    private javax.swing.JComboBox<String> cmbSubUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPdf;
    // End of variables declaration//GEN-END:variables
}
